apiVersion: chaos-mesh.org/v1alpha1
kind: PhysicalMachineChaos
metadata:
  name: stop-health-check-active-1695154919
  namespace: default
spec:
  action: user_defined
  address:
  - https://49.12.207.65:31768
  duration: 10m
  mode: all
  selector: {}
  user_defined:
    attackCmd: docker stop health_check-health_check-1
    recoverCmd: docker start health_check-health_check-1
