apiVersion: chaos-mesh.org/v1alpha1
kind: PhysicalMachineChaos
metadata:
  name: stress-cpu-inactive-1697110404
  namespace: default
spec:
  action: stress-cpu
  address:
  - https://116.203.199.187:31768
  duration: 10m
  mode: all
  selector: {}
  stress-cpu:
    load: 100
    workers: 100
