---
- name: install helm
  ansible.builtin.unarchive:
    src: https://get.helm.sh/helm-v3.12.2-linux-amd64.tar.gz
    dest: /usr/local/bin
    remote_src: yes
    include:
      - "linux-amd64/helm"
    extra_opts:
      - "--strip-components=1"

- name: install PyYAML pip module
  ansible.builtin.pip:
    name: PyYAML
    extra_args: --break-system-packages
