apiVersion: chaos-mesh.org/v1alpha1
kind: PhysicalMachineChaos
metadata:
  name: network-corrupt-wg-port-to-peers-active-1695204658
  namespace: default
spec:
  action: network-corrupt
  address:
  - https://128.140.41.88:31768
  duration: 10m
  mode: all
  network-corrupt:
    device: eth0
    ip-address: 46.142.84.227
    ip-protocol: udp
    percent: '75'
    source-port: '51820'
  selector: {}
