apiVersion: chaos-mesh.org/v1alpha1
kind: PhysicalMachineChaos
metadata:
  name: network-loss-wg-port-to-peers-active-1695531157
  namespace: default
spec:
  action: network-loss
  address:
  - https://128.140.41.88:31768
  duration: 10m
  mode: all
  network-loss:
    device: eth0
    ip-address: 46.142.85.34
    ip-protocol: udp
    percent: '100'
    source-port: '51820'
  selector: {}
