version: '3'

services:
  prometheus:
    image: prom/prometheus:latest
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/config
      - prometheus:/prometheus
    command: "--config.file=/config/prometheus.yml"

  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - grafana:/var/lib/grafana
    environment:
      GF_RENDERING_SERVER_URL: http://renderer:8081/render
      GF_RENDERING_CALLBACK_URL: http://grafana:3000/
      GF_LOG_FILTERS: rendering:debug

  renderer:
    image: grafana/grafana-image-renderer:latest
    restart: unless-stopped
    ports:
      - 8081
    depends_on:
      - grafana

  # dark background color:
  # replace "light" with "dark": https://github.com/IzakMarais/reporter/blob/632b60cdf33ff9085afb4ff701e7d7cfd526612c/grafana/api.go#L167
  # replace "Dockerfile": https://github.com/IzakMarais/reporter/issues/322#issuecomment-1110635549
  grafana-reporter:
    image: izakmarais/grafana-reporter
    restart: unless-stopped
    ports:
      - "8686:8686"
    command: "-ip grafana:3000"
    depends_on:
      - renderer

volumes:
  prometheus:
  grafana:
