{
 "title": "Chaos Experiments",
 "time": { "from": "2023-10-10T16:25:58.000Z", "to": "2023-10-10T17:42:52.000Z" },
 "panels": [
  { "title": "WireGuard", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "WireGuard: Peers",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count(time() - wireguard_latest_handshake_seconds{interface=\"wg0\", instance=\"10.1.0.1:9586\"} < 170)",
     "legendFormat": "Server 1"
    },
    {
     "expr": "count(time() - wireguard_latest_handshake_seconds{interface=\"wg0\", instance=\"10.2.0.1:9586\"} < 170)",
     "legendFormat": "Server 2"
    }
   ]
  },
  {
   "title": "WireGuard: Traffic received",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "sum(rate(wireguard_received_bytes_total{interface=\"wg0\", instance=\"10.1.0.1:9586\"}[$__rate_interval])*8)",
     "legendFormat": "Server 1"
    },
    {
     "expr": "sum(rate(wireguard_received_bytes_total{interface=\"wg0\", instance=\"10.2.0.1:9586\"}[$__rate_interval])*8)",
     "legendFormat": "Server 2"
    }
   ]
  },
  {
   "title": "WireGuard: Traffic transmitted",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 6, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "sum(rate(wireguard_sent_bytes_total{interface=\"wg0\", instance=\"10.1.0.1:9586\"}[$__rate_interval])*8)",
     "legendFormat": "Server 1"
    },
    {
     "expr": "sum(rate(wireguard_sent_bytes_total{interface=\"wg0\", instance=\"10.2.0.1:9586\"}[$__rate_interval])*8)",
     "legendFormat": "Server 2"
    }
   ]
  },
  { "title": "Health-Check", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Health-Check: Requests per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 29 },
   "targets": [
    {
     "expr": "sum(increase(flask_http_request_total{status=\"200\", instance=\"10.1.0.1:9200\"}[1m]))",
     "legendFormat": "Server 1"
    },
    {
     "expr": "sum(increase(flask_http_request_total{status=\"200\", instance=\"10.2.0.1:9200\"}[1m]))",
     "legendFormat": "Server 2"
    }
   ]
  },
  {
   "title": "Health-Check: Errors per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 37 },
   "targets": [
    {
     "expr": "sum(increase(flask_http_request_total{status!=\"200\", instance=\"10.1.0.1:9200\"}[1m]))",
     "legendFormat": "Server 1"
    },
    {
     "expr": "sum(increase(flask_http_request_total{status!=\"200\", instance=\"10.2.0.1:9200\"}[1m]))",
     "legendFormat": "Server 2"
    }
   ]
  },
  { "title": "Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Server: CPU",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 6, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode!=\"idle\", instance=\"10.1.0.1:9100\"}[$__rate_interval]))",
     "legendFormat": "Server 1"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode!=\"idle\", instance=\"10.2.0.1:9100\"}[$__rate_interval]))",
     "legendFormat": "Server 2"
    }
   ]
  },
  {
   "title": "Server: Memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 6, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"10.1.0.1:9100\"} - node_memory_MemFree_bytes{instance=\"10.1.0.1:9100\"} - (node_memory_Cached_bytes{instance=\"10.1.0.1:9100\"} + node_memory_Buffers_bytes{instance=\"10.1.0.1:9100\"} + node_memory_SReclaimable_bytes{instance=\"10.1.0.1:9100\"})",
     "legendFormat": "Server 1"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"10.2.0.1:9100\"} - node_memory_MemFree_bytes{instance=\"10.2.0.1:9100\"} - (node_memory_Cached_bytes{instance=\"10.2.0.1:9100\"} + node_memory_Buffers_bytes{instance=\"10.2.0.1:9100\"} + node_memory_SReclaimable_bytes{instance=\"10.2.0.1:9100\"})",
     "legendFormat": "Server 2"
    }
   ]
  },
  {
   "title": "Server: Traffic received",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 6, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(irate(node_network_receive_bytes_total{instance=\"10.1.0.1:9100\"}[$__rate_interval])*8)",
     "legendFormat": "Server 1"
    },
    {
     "expr": "sum(irate(node_network_receive_bytes_total{instance=\"10.2.0.1:9100\"}[$__rate_interval])*8)",
     "legendFormat": "Server 2"
    }
   ]
  },
  {
   "title": "Server: Traffic transmitted",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 6, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(irate(node_network_transmit_bytes_total{instance=\"10.1.0.1:9100\"}[$__rate_interval])*8)",
     "legendFormat": "Server 1"
    },
    {
     "expr": "sum(irate(node_network_transmit_bytes_total{instance=\"10.2.0.1:9100\"}[$__rate_interval])*8)",
     "legendFormat": "Server 2"
    }
   ]
  }
 ]
}