---
- name: generate wireguard peer firewall rules
  script: generate_firewall_rules.py --interface '{{ wireguard.interface | to_json }}' --peers '{{ wireguard.peers | to_json }}'
  register: result_peer_rules

- name: generate wireguard custom firewall rules
  script: generate_firewall_rules.py --custom-rules '{{ wireguard.custom_rules | default([], true) | to_json }}'
  register: result_custom_rules

- name: set facts for generated firewall rules
  set_fact:
    wireguard_peer_firewall_rules: "{{ result_peer_rules.stdout | from_json }}"
    wireguard_custom_firewall_rules: "{{ result_custom_rules.stdout | from_json }}"
