apiVersion: chaos-mesh.org/v1alpha1
kind: PhysicalMachineChaos
metadata:
  name: network-corrupt-health-check-port-to-other-server-inactive-1695514331
  namespace: default
spec:
  action: network-corrupt
  address:
  - https://49.12.207.65:31768
  duration: 10m
  mode: all
  network-corrupt:
    device: eth0
    egress-port: '80'
    ip-address: 128.140.41.88
    ip-protocol: tcp
    percent: '50'
  selector: {}
