apiVersion: chaos-mesh.org/v1alpha1
kind: PhysicalMachineChaos
metadata:
  name: server-shutdown-inactive-1695317797
  namespace: default
spec:
  action: user_defined
  address:
  - https://49.12.207.65:31768
  duration: 1s
  mode: all
  selector: {}
  user_defined:
    attackCmd: shutdown -h +1
    recoverCmd: 'true'
