---
- name: copy health_check dir
  ansible.builtin.copy:
    src: health_check
    dest: "{{ ansible_env.HOME }}"
    mode: 0644

- name: start health_check
  ansible.builtin.shell: "docker compose -f {{ ansible_env.HOME }}/health_check/docker-compose.yml up -d --build"

- name: copy check_other_servers.py
  ansible.builtin.copy:
    src: check_other_servers.py
    dest: /root/check_other_servers.py
    mode: 0744

- name: install setuptools and pip
  ansible.builtin.apt:
    name:
      - python3-setuptools
      - python3-pip
    state: latest
    update_cache: yes

- name: install hcloud python package
  ansible.builtin.pip:
    name: hcloud==1.28.0
    extra_args: --break-system-packages

- name: create check_other_servers cronjob
  ansible.builtin.cron:
    name: check_other_servers
    job: sleep $(( RANDOM \% 60 )) && /root/check_other_servers.py --token "{{ hetzner.api_token }}" --floating-ipv4 "{{ hetzner.floating_ipv4 }}" --floating-ipv6 "{{ hetzner.floating_ipv6 | default('') }}" --server-ips {{ hostvars[inventory_hostname]['groups']['servers'] | join(' ') }}
