global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets:
        - 'localhost:9090'

  - job_name: 'node_exporter'
    static_configs:
      - targets:
        - '10.1.0.1:9100'
        - '10.2.0.1:9100'

  - job_name: 'wireguard_exporter'
    static_configs:
      - targets:
        - '10.1.0.1:9586'
        - '10.2.0.1:9586'

  - job_name: 'health_check_exporter'
    static_configs:
      - targets:
        - '10.1.0.1:9200'
        - '10.2.0.1:9200'
